### ISSUE TITLE
图片尺寸问题

### ISSUE THREAD

**Issue by 1055169799** [kosakarin/hide_img#1]
有一个问题，生成的图片大小是按照第一张的尺寸计算的有一个问题，生成的图片大小是按照第一张的尺寸计算的，这导致如果第一张图片是一个小尺寸的表情包，则第二张图片就看不清楚了（另外，点开图片放大之后，会惊现第一张图片）![-3dca8c3c72a99d72.png](https://user-images.githubusercontent.com/41286675/147829768-bfd5cdbb-b444-43f5-b755-76e1e15b70eb.png)

**Comment by kosakarin** [comment]
逻辑是先将第二张图片等比例处理成和第一张图片差不多大小的图片，然后对二者进行补全，反正就是一张像素如果很低的话第二张的像素也会被拉低，这个可以后续改算法把图片处理成二者中较大的那个；
然后惊现第一张图片我不是很清楚是什么意思，这张图我也看不出来有什么情况，理论上目前明图和暗图不会有交集，除非我算法写错了

**Comment by 1055169799** [comment]
> 逻辑是先将第二张图片等比例处理成和第一张图片差不多大小的图片，然后对二者进行补全，反正就是一张像素如果很低的话第二张的像素也会被拉低，这个可以后续改算法把图片处理成二者中较大的那个；
> 然后惊现第一张图片我不是很清楚是什么意思，这张图我也看不出来有什么情况，理论上目前明图和暗图不会有交集，除非我算法写错了

就是当幻影坦克图片做出来之后。如果你对图片进行放大，就会在第二张图片的表面浮现第一张图，图1和图2是同时存在的。![Screenshot_2021-12-31-23-40-29-65_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://user-images.githubusercontent.com/41286675/147830901-6ed2dc9b-db87-413f-8039-0b3d85b450a7.jpg)![Screenshot_2021-12-31-23-40-35-28_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://user-images.githubusercontent.com/41286675/147830903-a2bdc851-df92-4355-9964-6c09652be9e0.jpg)![Screenshot_2021-12-31-23-40-47-70_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://user-images.githubusercontent.com/41286675/147830992-1bed5028-c9e2-457e-9ccf-d7eed5296f84.jpg)

**Comment by kosakarin** [comment]
> > 逻辑是先将第二张图片等比例处理成和第一张图片差不多大小的图片，然后对二者进行补全，反正就是一张像素如果很低的话第二张的像素也会被拉低，这个可以后续改算法把图片处理成二者中较大的那个；
> > 然后惊现第一张图片我不是很清楚是什么意思，这张图我也看不出来有什么情况，理论上目前明图和暗图不会有交集，除非我算法写错了
> 
> 就是当幻影坦克图片做出来之后。如果你对图片进行放大，就会在第二张图片的表面浮现第一张图，图1和图2是同时存在的。![Screenshot_2021-12-31-23-40-29-65_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://user-images.githubusercontent.com/41286675/147830901-6ed2dc9b-db87-413f-8039-0b3d85b450a7.jpg)![Screenshot_2021-12-31-23-40-35-28_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://user-images.githubusercontent.com/41286675/147830903-a2bdc851-df92-4355-9964-6c09652be9e0.jpg)![Screenshot_2021-12-31-23-40-47-70_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://user-images.githubusercontent.com/41286675/147830992-1bed5028-c9e2-457e-9ccf-d7eed5296f84.jpg)

这个原因我还真不太清楚，合理怀疑是qq压缩导致的，回头我本地生成一张直接保存到本地放大看看

**Comment by 1055169799** [comment]
> > > 逻辑是先将第二张图片等比例处理成和第一张图片差不多大小的图片，然后对二者进行补全，反正就是一张像素如果很低的话第二张的像素也会被拉低，这个可以后续改算法把图片处理成二者中较大的那个；
> > > 然后惊现第一张图片我不是很清楚是什么意思，这张图我也看不出来有什么情况，理论上目前明图和暗图不会有交集，除非我算法写错了
> > 
> > 就是当幻影坦克图片做出来之后。如果你对图片进行放大，就会在第二张图片的表面浮现第一张图，图1和图2是同时存在的。![Screenshot_2021-12-31-23-40-29-65_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://user-images.githubusercontent.com/41286675/147830901-6ed2dc9b-db87-413f-8039-0b3d85b450a7.jpg)![Screenshot_2021-12-31-23-40-35-28_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://user-images.githubusercontent.com/41286675/147830903-a2bdc851-df92-4355-9964-6c09652be9e0.jpg)![Screenshot_2021-12-31-23-40-47-70_9d26c6446fd7bb8e41d99b6262b17def.jpg](https://user-images.githubusercontent.com/41286675/147830992-1bed5028-c9e2-457e-9ccf-d7eed5296f84.jpg)
> 
> 这个原因我还真不太清楚，合理怀疑是qq压缩导致的，回头我本地生成一张直接保存到本地放大看看

好的靓仔，元旦快乐。✨🎉❤

**Comment by kosakarin** [comment]
现在会按照两张图片中横向像素较多的图片来合成了，例如图片a[1000,500],b[500,1000],最后生成的图片为[1000, 2000]
然后关于放大后表图会显示出来，我本地PS看了下，是没有问题的，应该是qq在过高放大比例的情况下背景会补白色导致的
